#!/usr/bin/env ruby

# Usage: script2md [FILE]...
# Usage: script2md example.sh > EXAMPLE.md

require 'script2md'
require 'open-uri'

  if /\Ahttps?:/ =~ ARGV[0]
    file_path = ARGV[0]
    language_type = file_path.match(/\.([a-z]+)\z/)[1] || nil
    filebody = OpenURI.open_uri(file_path).read
    puts Script2md.convert(filebody)
  else
    file_path = ARGV[0]
    language_type = file_path.match(/\.([a-z]+)\z/)[1] || nil
    filebody = File.read(file_path)
    puts Script2md.convert(filebody, language_type: language_type)
  end

